default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['postgres_host'] %>
  port: <%= ENV['postgres_port'] %>
  username: <%= ENV['postgres_user'] %>
  database: cinema
  password: <%= ENV['postgres_password'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
#  database: cinema_development

test:
  <<: *default
#  database: cinema_test

production:
  <<: *default
  database: cinema_production
  username: kender
  password: <%= ENV['CINEMA_DATABASE_PASSWORD'] %>
